Keyboard focus events and documentation
postlund/pyatv pull request #2031
Opened 2023-06-05 14:00 UTC by michalmo

This PR adds a listener interface for updating the focus state of the virtual keyboard, and documentation for the Keyboard interface as discussed in comments to #1905.

I've opted to not create a listener for text content, or to pass the current text as part of the focus state update since my testing has found this unreliable. The device only sends text updates for changes made through on screen clicks, not made over the API, and only appears to have started doing so in a patch release that occurred after developing the initial PR. Using text_get gets the actual content always by resetting the text input session before each request.

2023-06-05 23:44 UTC, IsakTheHacker approved these changes

2023-06-08 07:21 UTC, postlund requested changes
Looks good to me (with one minor exception comment)! 👍

2023-06-08 07:21 UTC, postlund commented on pyatv/interface.py
> +        raise NotImplementedError()
```suggestion
        raise exceptions.NotSupportedError()
```

2023-06-08 12:40 UTC, merged

2023-06-08 13:24 UTC, IsakTheHacker commented
@postlund When will you release a new version with this functionality included? I really need the focus events to finish my app

2023-06-08 13:25 UTC, postlund commented
@IsakTheHacker I can make a release later tonight.

2023-06-08 18:50 UTC, IsakTheHacker commented
That's awesome! Thank you so much

2023-06-08 19:58 UTC, postlund commented
@IsakTheHacker Release is cooking in #2039